### ISSUE TITLE
Problème avec TF1

### ISSUE THREAD

**Issue by FRony76** [spmjc/plugin.video.freplay#115]
Bonjour,
Depuis quelques jours TF1 ne fonctionne plus (extrait des logs): 
_21:05:26.164 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.freplay/?param=13477687&mode=play&channel=tf1&name=EXCLU+-+D%C3%A9couvrez+les+premi%C3%A8res+r%C3%A9p%C3%A9titions+de+Lenni-Kim+et+Marie+Denigot
21:05:26.164 T:1718612976   ERROR: InputStream: Error opening, plugin://plugin.video.freplay/?param=13477687&mode=play&channel=tf1&name=EXCLU+-+D%C3%A9couvrez+les+premi%C3%A8res+r%C3%A9p%C3%A9titions+de+Lenni-Kim+et+Marie+Denigot_
.
.
.
Il y a aussi ce message : 

_21:06:33.741 T:1341912048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error timed out>
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.freplay/default.py", line 152, in <module>
                                                url = globalvar.channels[channel][1].getVideoURL(channel, param)
                                              File "/home/osmc/.kodi/addons/plugin.video.freplay/resources/lib/channels/tf12.py", line 87, in getVideoURL
                                                timestamp = get_timestamp()
                                              File "/home/osmc/.kodi/addons/plugin.video.freplay/resources/lib/channels/tf12.py", line 72, in get_timestamp
                                                servertime = urllib2.urlopen('http://www.wat.tv/servertime').read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error timed out>
                                            -->End of Python script error report<--_

Est-ce que vous avez une idée ?
Ronald

**Comment by FRony76** [comment]
Erreur de config Unlocator

**Comment by spmjc** [comment]
Perso, j'utilise unodns.
Ça marche bien unlocator?

**Comment by FRony76** [comment]
Je vais essayer unodns pour voir. Unlocator marche pas trop mal.

**Comment by FRony76** [comment]
Plus de TF1 depuis ce soir (J'ai posté sur forum.mpdb.tv). Ca laggait et après un reboot, plus rien !
