### ISSUE TITLE
Les chaînes du groupe M6 ne fonctionnent plus

### ISSUE THREAD

**Issue by Flavien** [spmjc/plugin.video.freplay#86]
Lorsque j'éssaye d'accéder à n'importe quelle chaine du groupe M6 (6ter, M6, etc...), Kodi affiche une erreur et refuse de lister les émissions. Le log contient l'érreur suivante:

```
13:35:21.971 T:20128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "C:\Users\Flavien\AppData\Roaming\Kodi\addons\plugin.video.freplay\default.py", line 72, in <module>
                                                for chan,folder_param, folder_title, folder_icon, mode in globalvar.channels[channel][1].list_shows(channel,param):
                                              File "C:\Users\Flavien\AppData\Roaming\Kodi\addons\plugin.video.freplay\resources\lib\channels\6play.py", line 52, in list_shows
                                                categoryId = str(array['id'])
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
13:35:21.990 T:13660   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.freplay/?channel=6ter&mode=folder&param=none
13:35:21.991 T:13660   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/?channel=6ter&mode=folder&param=none) failed
```

Ceci est probablement du à un changement dans l'API de M6.

**Comment by sy6sy2** [comment]
Bonjour Flavien,

Oui l'API V1 de 6play ne fonctionne plus, tu peux mettre à jour directement le plugin avec la dernière version de GitHub ; j'ai fait les modifs pour passer sur la V2 (Cf. Dernière issue fermée et Commits des jours derniers ;-)

**Comment by sy6sy2** [comment]
Tu peux aussi suivre les derniers posts du forum http://media-passion.fr/add-ons-video/freplay-french-replay/ ;-)

**Comment by Flavien** [comment]
Ok, super. Est-ce qu'il est prévu de mettre à jour l'add-on sur le repo de passion XBMC?

**Comment by sy6sy2** [comment]
Pour la mise à jour sur le repo c'est SPM qui s'en occupe ;-)
Je pense qu'il le ferra prochainement oui.
