### ISSUE TITLE
Les chaines du groupe M6 ne fonctionnent plus

### ISSUE THREAD

**Issue by Flavien** [spmjc/plugin.video.freplay#90]
Quand j'essaye d'ouvrir une chaine du groupe M6, j'ai une erreur. Dans le log:

```
18:39:57.970 T:13652   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Failed to fetch the 6play catalog
                                            Traceback (most recent call last):
                                              File "C:\Users\Flavien\AppData\Roaming\Kodi\addons\plugin.video.freplay\default.py", line 119, in <module>
                                                for chan, folder_param, folder_title, folder_icon, mode in globalvar.channels[channel][1].list_shows(channel, param):
                                              File "C:\Users\Flavien\AppData\Roaming\Kodi\addons\plugin.video.freplay\resources\lib\channels\6play2.py", line 73, in list_shows
                                                raise Exception('Failed to fetch the 6play catalog')
                                            Exception: Failed to fetch the 6play catalog
                                            -->End of Python script error report<--
```

**Comment by xblond** [comment]
Le  paramètre limit semble avoir été restreint à 3 digits max soit 999

**Comment by spmjc** [comment]
C'est bien ca :+1: 
Merci
